### ISSUE TITLE
How to resize a object?

### ISSUE THREAD

**Issue by JonasPfeifer05** [JonasPfeifer05/rui#10]
How do you you think we should resize a Component?

**Comment by JonasPfeifer05** [comment]
Yea that sounds like a great solution. So the Component just stores its relative coords and when drawn calculate its absolute values. Did I understand that correct?
And are you going to implement that or should I do it?

**Comment by JonasPfeifer05** [comment]
And if we want to resize a Component we just change its relative Bounds?

**Comment by ToBinio** [comment]
yea i would say so, and i am gona start working on it

**Comment by JonasPfeifer05** [comment]
ok! Anything I could work on in the near futur?
