### ISSUE TITLE
i hate Option<>

### ISSUE THREAD

**Issue by ToBinio** [JonasPfeifer05/rui#13]
i once again have some problems becouse of the Option enum.
I dont know if i am missing something.
but i always run into problems when ussing it.

i would appreciate if you could have a look at the  #12 draft
there my main issue is that becouse the changed rendering function needs a mut-sef-ref the root component needs to be mutable.
This isnt a problem and i also can get a mut-ref from the option enum. but the problem starts becouse i also need a self ref in the render function so there is 1 mut-self-ref and one self-ref at the same time which isnt allowed.

btw... a simular problem is in the plain.rs with the quad

**Comment by JonasPfeifer05** [comment]
just a quick idea. Couldnt we just make a seperate function called update_size or so that gets the parent points and later we call the normal render function? Or does that also not work?

**Comment by JonasPfeifer05** [comment]
I havent tested it but looks like that will work:

First we remove the Option from our root. In der new() from state we create the root like so:

```
let state: State;

let mut layout_component = LayoutComponent::new(None,
                                                        (-0.7, 0.7),
                                                        (0.7, -0.7));

        let mut layout_component2 = LayoutComponent::new(Some(&layout_component),
                                                         (-1.0, 0.7),
                                                         (1.0, -1.0));

        let mut layout_component3 = LayoutComponent::new(Some(&layout_component2),
                                                         (0.0, 1.0),
                                                         (1.0, -1.0));

        let plain_component = PlainComponent::new(&layout_component,
                                                  (-1.0, 1.0),
                                                  (1.0, 0.7),
                                                  [1.0, 1.0, 0.0],
                                                  &device,
                                                  &state
        );

        ...

        Self {
            root: layout_component,
            surface,
            device,
            queue,
            config,
            size,
            last_mouse_position: (0.0, 0.0)
        }

```

The Component render function now can have a mut ref 
`fn render<'a>(&'a mut self, render_pass: &mut RenderPass<'a>);`

and in the render loop we just normally call the render function

I think this will work! Let me know if problems still accure

**Comment by ToBinio** [comment]
the problem is that the render function also needs a ref to the state so it can create a new quad if needed.

**Comment by JonasPfeifer05** [comment]
Will that be a problem? Dont think so?

**Comment by ToBinio** [comment]
the problem is when you get mut-ref from the state it needs a mut ref to it self and if the function then also needs a ref to it self. it has 2 self-ref one mut one not-mut which isnt allowed

**Comment by JonasPfeifer05** [comment]
What accactly do you need from state?

**Comment by ToBinio** [comment]
first i though like everything... but only the device and config... so i think it should be possible if i only use those

**Comment by JonasPfeifer05** [comment]
Yea just pass them spereatly or create a new struct that stores references to the important variables like device options usw and pass that to the function

**Comment by ToBinio** [comment]
uws is keine englisch abkürtzung! 😡

**Comment by JonasPfeifer05** [comment]
ETCCCCCCCC😡😡😡🤬🤬🤬😡😡🤯🤯🤯

**Comment by JonasPfeifer05** [comment]
😂

**Comment by ToBinio** [comment]
ok i think it should work now...
