### ISSUE TITLE
Approvements to shape

### ISSUE THREAD

**Issue by JonasPfeifer05** [JonasPfeifer05/rui#4]
I think we should be able to pass in the color of the figure. Also currently the shapes are streched. Are we going to change that or what did you think of?

**Comment by ToBinio** [comment]
color 100%

i think there should be possibility for both.
e.g. a background squar should probaly be screched couse it has to be relativ to the window size. A oval or text should probaly / defenetly not be streched. 
we could create a function which converters relativ possitons (-1; 1) to absolut once where the smaller / bigger size of the windows is in the range of (-1; 1) and the other matches the scale of that.

**Comment by JonasPfeifer05** [comment]
Ok! I also thought of that.
