### ISSUE TITLE
dublicated Vertex Structs

### ISSUE THREAD

**Issue by ToBinio** [JonasPfeifer05/rui#6]
currently the oval shape reuses the QuadVertex. which is weird.
the questions is do we want to keep it that way or split the shapes and VertexStructs?

**Comment by JonasPfeifer05** [comment]
There is a seperate traid to implement for custom Vertexes. But because the oval and Quad are using the same Vertex we could call it something like SimpleVertex for standart shapes. But I think the text or whatever may need more complex vertexes for what we need to implement new vertexes.
